### PR TITLE
Elden Ring and Death Stranding fix ported to ASI

### PR DESCRIPTION
**Pull request by TL431**

### CODE REVIEW

**Comment by illusion0001** [comment]
Needs conflict resolved in order for merge

**Comment by illusion0001** [comment]
`git rebase upstream/main` should work if you are using desktop app in combination with git

**Comment by illusion0001** [comment]
Or you can do it via the desktop UI too.

**Comment by TL431** [comment]
Weird, I can't see any conflict on the github pull request page.

I tried to rebase my branch with upstream/main, but it fails as it is already up to date. And yes I'm using the Github desktop app with git.

**Comment by illusion0001** [comment]
Go to repository and open with command prompt from the desktop app and run these commands:
```
git reset --HARD cec8037
git cherry-pick dc0939d
git cherry-pick 655dfe3
git push -f
```
The first command will reset the head (current commit) to the newest current main branch commit.
The second and third commit will pick the two new commits you added for this pr.
The fourth commit will force push your changes to the branch.

**Comment by TL431** [comment]
Done :) Thank you for your help

**Pull request merged**
